
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Post, Comment, UserProfile, Tag, Category, InterviewQuestion } from "@/types/database";

// Define our custom database schema to be used with the typed client
interface CustomDatabase {
  public: {
    Tables: {
      posts: {
        Row: Post;
        Insert: Omit<Post, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<Post, "id" | "created_at">>;
      };
      comments: {
        Row: Comment;
        Insert: Omit<Comment, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<Comment, "id" | "created_at">>;
      };
      profiles: {
        Row: UserProfile;
        Insert: Omit<UserProfile, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<UserProfile, "id" | "created_at">>;
      };
      tags: {
        Row: Tag;
        Insert: Omit<Tag, "id">;
        Update: Partial<Omit<Tag, "id">>;
      };
      categories: {
        Row: Category;
        Insert: Omit<Category, "id">;
        Update: Partial<Omit<Category, "id">>;
      };
      interview_questions: {
        Row: InterviewQuestion;
        Insert: Omit<InterviewQuestion, "id" | "created_at" | "updated_at">;
        Update: Partial<Omit<InterviewQuestion, "id" | "created_at">>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

const SUPABASE_URL = "https://rwgmzmiryjwbpyhmylqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Z216bWlyeWp3YnB5aG15bHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTQ5NjQsImV4cCI6MjA2MzQ3MDk2NH0.LuJHCsOYmkc0Nu5DqA7MimnM5WPVcfDm964h0krU8BI";

// We're using our CustomDatabase type instead of the generated Database type
export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
