
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwgmzmiryjwbpyhmylqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Z216bWlyeWp3YnB5aG15bHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTQ5NjQsImV4cCI6MjA2MzQ3MDk2NH0.LuJHCsOYmkc0Nu5DqA7MimnM5WPVcfDm964h0krU8BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// We're using the Database type from types.ts here, but our actual table
// definitions are in separate files to avoid modifying the read-only file
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
