// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://insekoorotngjhmsedzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imluc2Vrb29yb3RuZ2pobXNlZHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTQ2MjAsImV4cCI6MjA2MzY3MDYyMH0.kHjk4lr4NU7YsWKZ_GSRJAN5wP4FItlr6HG6yn_Vs78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);